spring.application.name=API_Tareas

spring.datasource.url=jdbc:mysql://bd-tareas.chmkomw8qbwj.us-east-1.rds.amazonaws.com:3306/BDTAREAS?useSSL=false&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=Usuario1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


